### ISSUE TITLE
Error: Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by mohitrakhade20** [mohitrakhade20/ValleyToken-cryptocurrency#1]
Err : 
```
 Contract: ValleyToken
    √ initialize the contract with correct values (794ms)
    √ sets the initial supply upon deployment (1314ms)
    √ transfers token ownership (664ms)
    √ approve token for delegated transfer (250ms)
    √ handles delegated token transfers (897ms)

  Contract: ValleyTokenSale
    √ initilizes the contract with correct values (244ms)
    √ facilitates token buying (908ms)
    1) ends token sale

    Events emitted during test:
    ---------------------------

    ValleyToken.Transfer(
      _from: <indexed> 0xDdf83Af046a9058A6617B459996A5c59D34EE186 (type: address),
      _to: <indexed> 0xD725E867C7BBe0792b12EaD07Ea73D426Aa9Fb39 (type: address),
      _value: 749990 (type: uint256)
    )


    ---------------------------


  7 passing (6s)
  1 failing

  1) Contract: ValleyTokenSale
       ends token sale:
     Error: Returned values aren't valid, did it run Out of Gas?
     at PromiEvent (C:\Users\Mohit\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\promievent.js:9:1)
      at TruffleContract.tokenPrice (C:\Users\Mohit\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\execute.js:120:1)
      at D:\blockchain\project\Init_coin_offering_CodingVALLY\token_sale\test\ValleyTokenSale.js:146:34
      at process._tickCallback (internal/process/next_tick.js:68:7)

```

ValleyTokenSale.sol file:
```
pragma solidity >=0.4.21 <0.7.0;

import "./ValleyToken.sol";


contract ValleyTokenSale {
    address payable admin;
    ValleyToken public tokenContract;
    uint256 public tokenPrice;
    uint256 public tokensSold;

    event Sell(address _buyer, uint256 _amount);

    constructor(ValleyToken _tokenContract, uint256 _tokenPrice) public {
        admin = msg.sender;
        tokenContract = _tokenContract;
        tokenPrice = _tokenPrice;
    }

    function multiply(uint256 x, uint256 y) internal pure returns (uint256 z) {
        require(y == 0 || (z = x * y) / y == x, " ");
    }

    function buyTokens(uint256 _numberOfTokens) public payable {
        require(msg.value == multiply(_numberOfTokens, tokenPrice), "");
        require(tokenContract.balanceOf(address(this)) >= _numberOfTokens, "");
        require(tokenContract.transfer(msg.sender, _numberOfTokens), "");

        tokensSold += _numberOfTokens;
        emit Sell(msg.sender, _numberOfTokens);
    }

    function endSale() public {
        require(msg.sender == admin, "");
        require(
            tokenContract.transfer(
                admin,
                tokenContract.balanceOf(address(this))
            ),
            ""
        );

        selfdestruct(admin);
    }
}
```

end token sale test in **ValleyTokenSale.js** :

```
it("ends token sale", function () {
    return ValleyToken.deployed()
      .then(function (instance) {
        // Grab token instance first
        tokenInstance = instance;
        return ValleyTokenSale.deployed();
      })
      .then(function (instance) {
        // Then grab token sale instance
        tokenSaleInstance = instance;
        // Try to end sale from account other than the admin
        return tokenSaleInstance.endSale({ from: buyer });
      })
      .then(assert.fail)
      .catch(function (error) {
        assert(
          error.message.indexOf("revert" >= 0, "must be admin to end sale")
        );
        // End sale as admin
        return tokenSaleInstance.endSale({ from: admin });
      })
      .then(function (receipt) {
        return tokenInstance.balanceOf(admin);
      })
      .then(function (balance) {
        assert.equal(
          balance.toNumber(),
          999990,
          "returns all unsold dapp tokens to admin"
        );
        // Check that token price was reset when selfDestruct was called
        return tokenSaleInstance.tokenPrice();
      })
      .then(function (price) {
        assert.equal(price.toNumber(), 0, "token price was reset");
      });
  });

```

**Comment by mohitrakhade20** [comment]
made these changes in **ends token sale** test and issue resolved

```
it("facilitates the endSale", () => {
    return ValleyToken.deployed()
      .then((instance) => {
        tokenInstance = instance;
        return ValleyTokenSale.deployed();
      })
      .then((instance) => {
        tokenSaleInstance = instance;
        return tokenSaleInstance.endSale({ from: buyer });
      })
      .then(assert.fail)
      .catch((error) => {
        assert(error.message, "cannot endSale from someone other than admin");
        return tokenSaleInstance.endSale({ from: admin });
      })
      .then((receipt) => {
        return tokenInstance.balanceOf(admin);
      })
      .then((balance) => {
        assert.equal(
          balance.toNumber(),
          999990,
          "balance left with admin after ending sale"
        );
        return tokenInstance.balanceOf(tokenSaleInstance.address);
      })
      .then((balance) => {
        assert.equal(balance.toNumber(), 0, "contract has been reset");
      });
  });
```
